# .github/workflows/main.yml
name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your desired version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Make sure you generate this!

    - name: Run Black formatter check
      run: black --check .

    - name: Run Flake8 linter
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Pytest tests
      run: pytest

    # If you had a deployment step, it would go here
    # - name: Deploy to Heroku
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     heroku deploy ...